AWSTemplateFormatVersion: "2010-09-09"
Description: "S# for CodePipeline"

Parameters:
  CustomParameter001:
    Type: "String"
    Default: "custom001"

Resources:
  # ------------------------------------------------------------#
  # S3::Bucket
  # ------------------------------------------------------------#
  S3BucketPipeline:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "s3-${CustomParameter001}-codepipeline"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  S3BucketPipeline:
    Value: !Ref S3BucketPipeline
    Export:
      Name: !Sub "s3-${CustomParameter001}-codepipeline"
  S3BucketPipelineArn:
    Value: !GetAtt S3BucketPipeline.Arn
    Export:
      Name: !Sub "s3-${CustomParameter001}-codepipeline-arn"
